### ISSUE TITLE
query couldn't use twice

### ISSUE THREAD

**Issue by daogangtang** [nickel-org/nickel.rs#201] opened 2015-04-28 10:32 UTC
```
 14     fn check_user<'a>(req: &mut Request, mut res: Response<'a>) -> MiddlewareResult<'a> {
 15         let account =  &*req.query("account", "null")[0];
 16 
 17         println!("--> {}", account);
 18         let password = &*req.query("password", "null")[0];
 19         println!("--> {}", password);
 20         
 21         res.send("Hello world! <a href='/register'>register</a>")
 22     }
```
```
Compiling newborn v0.1.0 (file:///home/mike/workspace/newborn)
examples/user_auth_4gotye.rs:18:26: 18:29 error: cannot borrow `*req` as mutable more than once at a time
examples/user_auth_4gotye.rs:18         let password = &*req.query("password", "null")[0];
                                                         ^~~
examples/user_auth_4gotye.rs:15:26: 15:29 note: previous borrow of `*req` occurs here; the mutable borrow prevents subsequent moves, borrows, or modification of `*req` until the borrow ends
examples/user_auth_4gotye.rs:15         let account =  &*req.query("account", "null")[0];
                                                         ^~~
examples/user_auth_4gotye.rs:22:6: 22:6 note: previous borrow ends here
examples/user_auth_4gotye.rs:14     fn check_user<'a>(req: &mut Request, mut res: Response<'a>) -> MiddlewareResult<'a> {
...
examples/user_auth_4gotye.rs:22     } 
                                    ^
error: aborting due to previous error
Could not compile `newborn`.
```

**Comment by Ryman** [comment] 2015-04-28 13:17
Closing as duplicate of #186, which has a proposed for of #195

**Closed by Ryman** 2015-04-28 13:17 UTC
